apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    service: backend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5001
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nathan2820/backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: DB_PASSWORD
              value: "$DB_PASSWORD"
            - name: DATABASE_URI
              value: "$DATABASE_URI"
            - name: SECRET_KEY
              value: "$SECRET_KEY"
