apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    events{}
    http {
      server {
        listen 80;
        root /PracticalProject;
        index index.html;
        include /etc/nginx/mime.types;
        location / {
          proxy_pass http://flask-app:5000;
        }
      }
    }
